"""POST /api/v1/auth/invitations/accept — set initial password from invite link.

The invite token is generated by `POST /api/v1/employees` (an authenticated
supplier-admin operation). Tests below either:
- create a real token via the employees flow (covered in tests/employees/),
- exercise the negative responses with synthetic tokens.

For the positive end-to-end (real token → accept → login as the new
employee) see tests/employees/test_invite.py — keeping the cross-module
flow in one place avoids fixture duplication.
"""

from __future__ import annotations

import pytest

from api.client import ApiClient
from api.endpoints import auth as auth_ep
from api.schemas import AcceptInvitationRequest
from config.settings import Settings


@pytest.mark.negative
def test_accept_with_unknown_token_returns_410(
    api_client: ApiClient,
    settings: Settings,
) -> None:
    """Per swagger: unknown / expired / used / revoked → 410."""
    with api_client.expect_error(410):
        auth_ep.accept_invitation(
            api_client,
            AcceptInvitationRequest(
                token="bogus-token-that-was-never-issued",
                password=settings.default_test_password,
            ),
        )


@pytest.mark.negative
@pytest.mark.parametrize(
    "password",
    ["", "short", "lowercase1!", "Password!", "Password1"],
    ids=["empty", "too-short", "no-upper", "no-digit", "no-symbol"],
)
def test_accept_rejects_weak_password(
    api_client: ApiClient,
    password: str,
) -> None:
    """Server enforces Keycloak password policy — 400 before token lookup."""
    with api_client.expect_error(400):
        api_client.post(
            "/api/v1/auth/invitations/accept",
            json={"token": "any-token", "password": password},
            expect_status=204,
        )


@pytest.mark.negative
@pytest.mark.parametrize(
    "body",
    [{}, {"token": "x"}, {"password": "P@ssw0rd!"}],
    ids=["empty", "missing-password", "missing-token"],
)
def test_accept_with_missing_fields_returns_400(
    api_client: ApiClient,
    body: dict[str, str],
) -> None:
    with api_client.expect_error(400):
        api_client.post("/api/v1/auth/invitations/accept", json=body, expect_status=204)
